[env]
lib_deps =
  Wire
  xreef/PCF8574 library @ ^2.4.0
  ; OneButton - button handling library, used e.g. in TTGO T-Beam
  ; releases https://github.com/mathertel/OneButton/releases
;   mathertel/OneButton @ ^2.6.2
